edition = "2024"

max_width = 120
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
use_field_init_shorthand = true
reorder_impl_items = true
