[package]
name = "karmaio-examples"
version = "0.0.0"
publish = false
edition = "2024"
license = "MIT OR Apache-2.0"

[features]
default = ["full"]
full = ["fs", "macros", "net", "process", "signal", "bytes", "memmap2", "tls"]
fs = ["karmaio/fs"]
macros = ["karmaio/macros"]
net = ["karmaio/net"]
process = ["karmaio/process"]
signal = ["karmaio/signal"]
bytes = ["karmaio/bytes"]
memmap2 =["karmaio/memmap2"]
tls = ["karmaio/tls"]

[dependencies]
karmaio = { path = "../karmaio", default-features = false }

[[example]]
name = "hello_world"
path = "hello_world.rs"
required-features = ["macros", "net"]

[[example]]
name = "echo_tcp"
path = "echo_tcp.rs"
required-features = ["macros", "net"]

[[example]]
name = "echo_tcp_multi"
path = "echo_tcp_multi.rs"
required-features = ["macros", "net"]

[[example]]
name = "accept_multi"
path = "accept_multi.rs"
required-features = ["macros", "net"]

[[example]]
name = "framed_echo"
path = "framed_echo.rs"
required-features = ["macros", "net"]

[[example]]
name = "udp_echo"
path = "udp_echo.rs"
required-features = ["macros", "net"]

[[example]]
name = "udp_client"
path = "udp_client.rs"
required-features = ["macros", "net"]

[[example]]
name = "file_operations"
path = "file_operations.rs"
required-features = ["fs", "macros"]

[[example]]
name = "timer"
path = "timer.rs"
required-features = ["macros"]

[[example]]
name = "process"
path = "process.rs"
required-features = ["macros", "process"]

[[example]]
name = "signal"
path = "signal.rs"
required-features = ["macros", "signal"]

[[example]]
name = "runtime_builder"
path = "runtime_builder.rs"

[[example]]
name = "echo_tcp_recv_multi"
path = "echo_tcp_recv_multi.rs"
required-features = ["macros", "net"]

[[example]]
name = "spawn_tasks"
path = "spawn_tasks.rs"

[[example]]
name = "tls_client"
path = "tls_client.rs"
required-features = ["macros", "net", "tls"]

[[example]]
name = "tls_server"
path = "tls_server.rs"
required-features = ["macros", "net", "tls"]
